### ISSUE TITLE
speaker media muted

### ISSUE THREAD

**Issue by ghost** [anton-arnold/xoverrideheadphonejackdetection#3]
Whenever the module is active, there is no media sound coming out of the speakers. Notifications still works.

**Comment by anton-arnold** [comment]
@castielthe5kgod can you provide some more information?
Which Android/Custom ROM version do you use?
Which speaker do you refer to? 
My interpretation of your issue is the following constellation: module active, override enabled=1, connection state: nothing and the phones loudspeaker works for notification sounds but not for your music app (which? tested different ones?).
Volume is turned up I guess? (some systems may switch to a different volume control depending on the connection state)
Does this represent your problem? Can you copy some Xposed Logs of this module in this issue?
You find them in the Xposed Installer app in the menu (swipe screen from left to right)

**Comment by ghost** [comment]
Wow, sorry for the so late response. I completely forgot to reply. Long story short, I kind of figured out how to use the module. The problem was that I was headphone mode, and would use "Lesser AudioSwitch" to put it on speaker if I took my headphones out but was too lazy to switch it in your module. What happened was that I had to put the call in Speaker mode to hear or plug earbuds in (because I was still in headphone mode). I have a question, is there a way to automate this with tasker? Or to use the variables you put in the readme? I use your module like SoundAbout used to, to use the phone microphone instead of the earbuds ones because my headphone jack is borked and records random noise. Thank you! Your module works as intended, I just have to follow your steps of switching to "nothing" if I want to switch modes of course. Sorry for the late response, really sorry!

**Comment by anton-arnold** [comment]
@castielthe5kgod I try to figure out your usecase, can you confirm or correct it?
Your phone does correct detection of a cable plugged in or out.
You want to use headphone mode (speaker only) instead of headset mode (speaker+mic).
But you'd like to have the automatic switch back to the default built in speaker if the cable is unplugged.

**Comment by ghost** [comment]
exactly, just automatic switch between "nothing" and "headphone". I tried playing with tasker and the adb commands you wrote but to be honest I dont really understand them lol.

**Comment by anton-arnold** [comment]
@castielthe5kgod I updated the code to support your usecase. the apk is uploaded to the Xposed repository. If you use FDroid repo it may need some time to be updated there. Can you check if it works as desired?

**Comment by ghost** [comment]
Omg, as I opened exposed manager I saw the update. okay I will try

**Comment by ghost** [comment]
Okay so i tried it, I had override enabled, hybrid mode and headphone all checked and pressed apply. It stayed on headphone the whole time.

**Comment by ghost** [comment]
As in it wouldn't switch to "nothing". I also tried to plug and unplug a couple of times.

**Comment by anton-arnold** [comment]
@castielthe5kgod Okay, I couldn't test it good with my device since the headphone jack detection is broken. I'll check it again with another device within the next days.
Just to make sure: Did you reboot your phone after updating the module?
Can you paste the xposed installers logging messages if you plug in/out the cable with override and hybrid mode active?

**Comment by ghost** [comment]
1.Yes I did.
2.I am not sure how to do that, let me google it. Is it module logs? or verbose logs?

**Comment by ghost** [comment]
[EdXposed_Module_error_20191201_095209.log](https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/3908317/EdXposed_Module_error_20191201_095209.log)
[EdXposed_Verbose_all_20191201_095213.log](https://github.com/anton-arnold/xoverrideheadphonejackdetection/files/3908318/EdXposed_Verbose_all_20191201_095213.log)

**Comment by anton-arnold** [comment]
@castielthe5kgod ok I think I found the problem. can you check v1.5 if it works now correctly?

**Comment by ghost** [comment]
It works! Thank you! Last thing and sorry to bother you again. But is there anyway to make the app enable the override in hybrid mode when the phone boots? Is there maybe an adb command I can do with Tasker when my phone boots up? (Instead of enabling the override everytime I reboot my phone)

**Comment by anton-arnold** [comment]
@castielthe5kgod the configuration is already supposed to be saved and restored upon reboot. it wont show them on the settings gui though (that is part of the open other issue). can you see these 'hybrid mode' log messages after reboot if you plug in and out the cable? it might be that the config storage mechanism does not support android 10 with edxposed. I think in a few weeks I'm going to replace my phone then I can upgrade this one to android 10 but currently I need it in a working condition

**Comment by ghost** [comment]
I confirm, with android 10 and edxposed. with works correclty! saving and all. It keeps with reboots. Thanks!
